# -*- coding: utf-8 -*-
"""
Schema.org (JSON-LD) structured-data injector for the Schild Family Archive.

Reads each page's own already-generated <title>, <meta name="description">,
canonical URL, and og:image (all produced by inject_social_meta.py, which
must run first) so this script never invents copy — it only maps that
existing content into the right schema.org type per page:

  - homepage            -> WebSite + Organization (as an @graph)
  - /history/people/X/  -> Person   (using history-data.js for extra fields)
  - /history/places/X/  -> Place    (using history-data.js for extra fields)
  - /history/stories/X/ -> Article  (using history-data.js for extra fields)
  - every other page     -> CollectionPage (title/description only)

history-data.js is a plain JS object literal (window.HistoryData = {...});
it's dumped to JSON via Node first (see HISTORY_DATA_JSON) rather than
parsed by hand.

Idempotent: re-running updates the previously generated block in place
rather than duplicating it. Safe to re-run after editing history-data.js
or after inject_social_meta.py changes an image/description.
"""
import glob
import html
import json
import os
import re

ROOT = "/tmp/schildfamily-site"
SITE_URL = "https://schildfamily.com"
HISTORY_DATA_JSON = "/tmp/history-data.json"
LOGO_URL = f"{SITE_URL}/assets/shield.svg"
SITE_NAME = "The Schild Family Archive"

START_MARK = "<!-- SCHEMA.ORG STRUCTURED DATA (generated by scripts/inject_schema_org.py — do not hand-edit; edit history-data.js / page title+description and re-run instead) -->"
END_MARK = "<!-- /SCHEMA.ORG STRUCTURED DATA -->"


def load_history_data():
    with open(HISTORY_DATA_JSON, encoding="utf-8") as f:
        return json.load(f)


def unesc(s):
    """Decode the HTML entities used in history-data.js / page meta tags
    into plain text, appropriate for JSON-LD string values."""
    if s is None:
        return None
    return html.unescape(s).strip()


def route_for(path):
    rel = os.path.relpath(path, ROOT)
    if rel == "index.html":
        return "/"
    return "/" + rel[: -len("index.html")]


def extract(html_src, tag_pattern):
    m = re.search(tag_pattern, html_src)
    return m.group(1) if m else None


def page_meta(html_src):
    title = unesc(extract(html_src, r"<title>(.*?)</title>"))
    desc = unesc(extract(html_src, r'<meta name="description" content="(.*?)"\s*>'))
    canonical = extract(html_src, r'<link rel="canonical" href="(.*?)"\s*>')
    image = extract(html_src, r'<meta property="og:image" content="(.*?)"\s*>')
    return title, desc, canonical, image


def organization_block():
    return {"@type": "Organization", "name": SITE_NAME, "url": SITE_URL + "/", "logo": LOGO_URL}


def build_homepage(title, desc, canonical):
    return {
        "@context": "https://schema.org",
        "@graph": [
            {"@type": "WebSite", "name": SITE_NAME, "url": canonical or SITE_URL + "/", "description": desc},
            organization_block(),
        ],
    }


def build_person(pid, D, title, desc, canonical, image):
    p = D["people"].get(pid)
    if not p:
        return None
    obj = {
        "@context": "https://schema.org",
        "@type": "Person",
        "name": unesc(p.get("name")),
        "familyName": "Schild",
        "description": desc or unesc(p.get("summary")),
        "url": canonical,
    }
    if image:
        obj["image"] = image
    if p.get("birthPlace"):
        obj["birthPlace"] = unesc(p["birthPlace"])
    return obj


def build_place(pid, D, title, desc, canonical, image):
    p = D["places"].get(pid)
    if not p:
        return None
    obj = {
        "@context": "https://schema.org",
        "@type": "Place",
        "name": unesc(p.get("name")),
        "description": desc or unesc(p.get("summary")),
        "url": canonical,
    }
    if image:
        obj["image"] = image
    if p.get("region"):
        obj["containedInPlace"] = {"@type": "AdministrativeArea", "name": unesc(p["region"])}
    return obj


def build_story(sid, D, title, desc, canonical, image):
    s = D["stories"].get(sid)
    if not s:
        return None
    obj = {
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": unesc(s.get("title")) or title,
        "description": desc or unesc(s.get("teaser")),
        "url": canonical,
        "author": organization_block(),
        "publisher": organization_block(),
    }
    if image:
        obj["image"] = image
    return obj


def build_collection_page(title, desc, canonical):
    return {
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        "name": title,
        "description": desc,
        "url": canonical,
    }


def build_schema(route, path, D):
    html_src = open(path, encoding="utf-8").read()
    title, desc, canonical, image = page_meta(html_src)
    if not title:
        return None, html_src

    m = re.match(r"^/history/(people|places|stories)/([^/]+)/$", route)
    if route == "/":
        obj = build_homepage(title, desc, canonical)
    elif m:
        kind, entity_id = m.groups()
        builder = {"people": build_person, "places": build_place, "stories": build_story}[kind]
        obj = builder(entity_id, D, title, desc, canonical, image)
        if obj is None:
            obj = build_collection_page(title, desc, canonical)
    else:
        obj = build_collection_page(title, desc, canonical)

    return obj, html_src


def process(path, D):
    route = route_for(path)
    obj, html_src = build_schema(route, path, D)
    if obj is None:
        print("SKIP (no title/description found):", route)
        return False

    payload = json.dumps(obj, ensure_ascii=False, indent=2)
    block = f'{START_MARK}\n<script type="application/ld+json">\n{payload}\n</script>\n{END_MARK}'

    if START_MARK in html_src:
        pattern = re.compile(re.escape(START_MARK) + r".*?" + re.escape(END_MARK), re.S)
        new_html = pattern.sub(block, html_src)
        action = "updated"
    else:
        new_html = html_src.replace("</head>", block + "\n</head>", 1)
        action = "inserted"

    if new_html != html_src:
        open(path, "w", encoding="utf-8").write(new_html)
        print(f"{action}: {route}")
        return True
    return False


if __name__ == "__main__":
    D = load_history_data()
    files = sorted(glob.glob(os.path.join(ROOT, "**", "index.html"), recursive=True))
    changed = 0
    for f in files:
        if process(f, D):
            changed += 1
    print(f"\n{changed}/{len(files)} pages updated.")
